# Generated by Django 4.2.11 on 2024-04-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_childmuseum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('ExhibitID', models.IntegerField(primary_key=True, serialize=False)),
                ('ExhibitName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelTable(
            name='childmuseum',
            table='ChildMuseum',
        ),
    ]
