# Generated by Django 4.2.11 on 2024-04-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_exhibit_alter_childmuseum_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exhibit',
            table='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        
    ]
