# Generated by Django 4.2.11 on 2024-04-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_exhibit_alter_childmuseum_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exhibit',
            table='Exhibit',
        ),
    ]
